name: Publish NuGet Package

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Pack nuget package
      run: dotnet pack -c Release
    - name: Publish nuget package
      env:
        API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push brain-fxxk-core/bin/Release/BFCore.*.nupkg -k $API_KEY -s https://api.nuget.org/v3/index.json --skip-duplicate
